import { CourseDetails, CourseFiltersMetadata } from '../types/course-discovery.types';

export const mockCatalogCourses: CourseDetails[] = [
  {
    id: 'course-1',
    title: 'Satellite Meteorology & INSAT-3DR Multispectral Imagery',
    slug: 'satellite-meteorology-insat-3dr',
    description:
      'Comprehensive operational course on interpreting INSAT-3DR visible, thermal infrared, and water vapor channels for cloud classification, rapid convection detection, and derived atmospheric motion vectors.',
    thumbnailUrl: null,
    category: 'SATELLITE_METEOROLOGY',
    difficulty: 'INTERMEDIATE',
    durationMinutes: 1920, // 32 hours
    status: 'PUBLISHED',
    publishedAt: '2024-01-15T00:00:00.000Z',
    isEnrolled: true,
    enrollmentStatus: 'IN_PROGRESS',
    trainer: {
      id: 'trainer-1',
      name: 'Prof. A. Sharma',
      designation: 'Senior Scientist / Satellite Division',
      organizationName: 'Space Applications Centre (ISRO) & MoES',
      avatarUrl: null,
    },
    modulesCount: 4,
    lessonsCount: 24,
    objectives: [
      'Master rapid-scan image interpretation across 6 spectral channels of INSAT-3DR.',
      'Identify convective cloud tops, overshooting tops, and cold-U signatures for severe storm nowcasting.',
      'Utilize water vapor channel imagery to diagnose upper-tropospheric jet streams and potential vorticity anomalies.',
      'Generate quantitative products including Cloud Motion Vectors (CMVs) and Outgoing Longwave Radiation (OLR).',
    ],
    modules: [
      {
        id: 'mod-1',
        title: 'Module 1: Principles of Meteorological Satellite Remote Sensing',
        description: 'Orbits, spectral bands, and radiative transfer fundamentals.',
        orderIndex: 1,
        lessons: [
          {
            id: 'les-1',
            title: 'Geostationary vs. Polar Orbiting Platforms',
            description: 'Orbital geometry and temporal resolution.',
            durationMinutes: 45,
            orderIndex: 1,
            isPreview: true,
          },
          {
            id: 'les-2',
            title: 'INSAT-3DR Imager & Sounder Payloads',
            description: 'Technical sensor specs and channel characteristics.',
            durationMinutes: 50,
            orderIndex: 2,
            isPreview: false,
          },
          {
            id: 'les-3',
            title: 'Visible Channel Reflection & Albedo Analysis',
            description: 'Low cloud and fog identification.',
            durationMinutes: 45,
            orderIndex: 3,
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod-2',
        title: 'Module 2: Thermal Infrared & Water Vapor Interpretation',
        description: 'Atmospheric moisture profiling and deep convection diagnostics.',
        orderIndex: 2,
        lessons: [
          {
            id: 'les-4',
            title: 'Brightness Temperature & Cloud Top Height Estimation',
            description: 'Infrared calibration methods.',
            durationMinutes: 55,
            orderIndex: 1,
            isPreview: false,
          },
          {
            id: 'les-5',
            title: 'Middle & Upper Tropospheric Water Vapor Dynamics',
            description: 'Dry slots, moisture plumes, and deformation zones.',
            durationMinutes: 60,
            orderIndex: 2,
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod-3',
        title: 'Module 3: Severe Weather Signatures & Convective Initiation',
        description: 'Operational tracking of tropical thunderstorms and cyclones.',
        orderIndex: 3,
        lessons: [
          {
            id: 'les-6',
            title: 'Enhanced-V and Overshooting Top Detection',
            description: 'Severe convective storm hallmarks.',
            durationMinutes: 65,
            orderIndex: 1,
            isPreview: false,
          },
          {
            id: 'les-7',
            title: 'Tropical Cyclone Central Dense Overcast (CDO) Analysis',
            description: 'Dvorak intensity satellite techniques.',
            durationMinutes: 70,
            orderIndex: 2,
            isPreview: false,
          },
        ],
      },
    ],
    prerequisites: [
      {
        id: 'prereq-1',
        title: 'Synoptic Meteorology & Chart Analysis Fundamentals',
        slug: 'synoptic-meteorology-chart-analysis',
        category: 'SYNOPTIC_METEOROLOGY',
        difficulty: 'BEGINNER',
      },
    ],
    competencies: [
      {
        id: 'comp-1',
        name: 'INSAT-3DR Satellite Imagery',
        code: 'INSAT_3DR_SATELLITE_IMAGERY',
        category: 'SATELLITE_METEOROLOGY',
        targetLevel: 3,
      },
      {
        id: 'comp-2',
        name: 'Severe Storm Nowcasting',
        code: 'SEVERE_WEATHER_NOWCASTING',
        category: 'SEVERE_WEATHER',
        targetLevel: 3,
      },
    ],
  },
  {
    id: 'course-2',
    title: 'Numerical Weather Prediction & WRF-ARW Ensemble Modeling',
    slug: 'nwp-wrf-arw-ensemble-modeling',
    description:
      'Hands-on operational forecasting course covering the Weather Research and Forecasting (WRF) model, physical parameterization schemes, boundary layer physics, and ensemble probabilistic prediction.',
    thumbnailUrl: null,
    category: 'NUMERICAL_MODELING',
    difficulty: 'ADVANCED',
    durationMinutes: 2400, // 40 hours
    status: 'PUBLISHED',
    publishedAt: '2024-02-01T00:00:00.000Z',
    isEnrolled: false,
    enrollmentStatus: null,
    trainer: {
      id: 'trainer-2',
      name: 'Dr. K. Radhakrishnan',
      designation: 'Lead Scientist / Modeling Division',
      organizationName: 'National Centre for Medium Range Weather Forecasting (NCMRWF)',
      avatarUrl: null,
    },
    modulesCount: 5,
    lessonsCount: 25,
    objectives: [
      'Configure the WRF Preprocessing System (WPS) and domain nesting over the Indian subcontinent.',
      'Evaluate cumulus parameterization (Kain-Fritsch, Grell) and microphysics schemes for monsoon rain prediction.',
      'Interpret multi-model ensemble spread and probability of exceedance maps for extreme rainfall events.',
      'Verify model forecasts against observed IMD automatic weather station and Doppler radar data.',
    ],
    modules: [
      {
        id: 'mod-2-1',
        title: 'Module 1: WRF Architecture and Governing Equations',
        description: 'Non-hydrostatic dynamics and vertical coordinate formulation.',
        orderIndex: 1,
        lessons: [
          {
            id: 'les-2-1',
            title: 'Equations of Atmospheric Motion in WRF',
            description: 'Momentum, continuity, and thermodynamic conservation.',
            durationMinutes: 60,
            orderIndex: 1,
            isPreview: true,
          },
          {
            id: 'les-2-2',
            title: 'Domain Grid Nesting and Resolution Scaling',
            description: 'Coarse 9km to fine 3km convective permitting domains.',
            durationMinutes: 60,
            orderIndex: 2,
            isPreview: false,
          },
        ],
      },
      {
        id: 'mod-2-2',
        title: 'Module 2: Physics Parameterization Suites',
        description: 'Sub-grid scale physical representations.',
        orderIndex: 2,
        lessons: [
          {
            id: 'les-2-3',
            title: 'Planetary Boundary Layer (PBL) Schemes',
            description: 'YSU vs. Mellor-Yamada-Janjic formulations.',
            durationMinutes: 60,
            orderIndex: 1,
            isPreview: false,
          },
          {
            id: 'les-2-4',
            title: 'Microphysics & Cloud Radiation Coupling',
            description: 'WSM6 and Thompson microphysics options.',
            durationMinutes: 60,
            orderIndex: 2,
            isPreview: false,
          },
        ],
      },
    ],
    prerequisites: [
      {
        id: 'prereq-2',
        title: 'Atmospheric Thermodynamics and Mathematical Modeling',
        slug: 'atmospheric-thermodynamics-modeling',
        category: 'PHYSICAL_METEOROLOGY',
        difficulty: 'INTERMEDIATE',
      },
    ],
    competencies: [
      {
        id: 'comp-3',
        name: 'NWP Model Interpretation (WRF/GFS)',
        code: 'NWP_MODEL_INTERPRETATION',
        category: 'NUMERICAL_MODELING',
        targetLevel: 3,
      },
      {
        id: 'comp-4',
        name: 'Data Assimilation Techniques',
        code: 'DATA_ASSIMILATION',
        category: 'NUMERICAL_MODELING',
        targetLevel: 2,
      },
    ],
  },
  {
    id: 'course-3',
    title: 'Doppler Weather Radar (DWR) Calibration & Velocity De-aliasing',
    slug: 'doppler-weather-radar-calibration',
    description:
      'Specialized curriculum on S-band and C-band Doppler Weather Radar operations, raw I/Q signal processing, dual-polarization moments, and radial velocity folding correction in severe storm environments.',
    thumbnailUrl: null,
    category: 'RADAR_METEOROLOGY',
    difficulty: 'OPERATIONAL',
    durationMinutes: 1680, // 28 hours
    status: 'PUBLISHED',
    publishedAt: '2024-02-10T00:00:00.000Z',
    isEnrolled: false,
    enrollmentStatus: null,
    trainer: {
      id: 'trainer-3',
      name: 'Smt. P. Verma',
      designation: 'Director / Radar Operations',
      organizationName: 'IMD Central Training Institute, Pashan, Pune',
      avatarUrl: null,
    },
    modulesCount: 4,
    lessonsCount: 20,
    objectives: [
      'Calibrate radar receiver sensitivity and transmitter pulse repetition frequency (PRF).',
      'Resolve Nyquist velocity ambiguity using multi-PRF unfolding algorithms in high-shear regimes.',
      'Differentiate meteorological echoes from ground clutter, anomalous propagation (AP), and sea clutter.',
      'Identify supercell mesocyclones, tornado vortex signatures (TVS), and bow echo rear-inflow jets.',
    ],
    modules: [
      {
        id: 'mod-3-1',
        title: 'Module 1: Radar Engineering and Hardware Calibration',
        description: 'Transmitters, waveguides, antennas, and receiver subsystems.',
        orderIndex: 1,
        lessons: [
          {
            id: 'les-3-1',
            title: 'S-band vs. C-band Radar Propagation Characteristics',
            description: 'Attenuation and beam blockage.',
            durationMinutes: 45,
            orderIndex: 1,
            isPreview: true,
          },
          {
            id: 'les-3-2',
            title: 'Radar Equation and Power Calibration with Sun Tracking',
            description: 'Antenna gain and receiver noise floor.',
            durationMinutes: 55,
            orderIndex: 2,
            isPreview: false,
          },
        ],
      },
    ],
    prerequisites: [],
    competencies: [
      {
        id: 'comp-5',
        name: 'Doppler Weather Radar (DWR)',
        code: 'DOPPLER_WEATHER_RADAR',
        category: 'RADAR_METEOROLOGY',
        targetLevel: 3,
      },
      {
        id: 'comp-6',
        name: 'Severe Storm Nowcasting',
        code: 'SEVERE_WEATHER_NOWCASTING',
        category: 'SEVERE_WEATHER',
        targetLevel: 3,
      },
    ],
  },
  {
    id: 'course-4',
    title: 'Operational Severe Convective Storm Nowcasting (0-3 Hours)',
    slug: 'severe-convective-storm-nowcasting',
    description:
      'Real-time operational forecasting protocol integrating lightning flash rates, multi-radar mosaics, rapid-scan satellite loops, and surface thermodynamic indices for localized thunderstorm warnings.',
    thumbnailUrl: null,
    category: 'SEVERE_WEATHER',
    difficulty: 'OPERATIONAL',
    durationMinutes: 1800, // 30 hours
    status: 'PUBLISHED',
    publishedAt: '2024-02-15T00:00:00.000Z',
    isEnrolled: false,
    enrollmentStatus: null,
    trainer: {
      id: 'trainer-4',
      name: 'Dr. M. Mohapatra',
      designation: 'Director General of Meteorology',
      organizationName: 'India Meteorological Department HQ New Delhi',
      avatarUrl: null,
    },
    modulesCount: 4,
    lessonsCount: 18,
    objectives: [
      'Diagnose thermodynamic destabilization using CAPE, CIN, and Lifted Index from radiosonde tephigrams.',
      'Track convective storm lifecycle from cumulus initiation to mature multicell cluster and squall line.',
      'Issue actionable Color-Coded Severe Weather Warnings (Yellow/Orange/Red) with high lead time.',
      'Coordinate with National Disaster Management Authority (NDMA) for public alert broadcasts.',
    ],
    modules: [
      {
        id: 'mod-4-1',
        title: 'Module 1: Convective Atmospheric Instability & Pre-storm Environments',
        description: 'Sounding analysis and boundary layer forcing.',
        orderIndex: 1,
        lessons: [
          {
            id: 'les-4-1',
            title: 'Tephigram Analysis and Convective Available Potential Energy',
            description: 'Calculation of surface-based and most-unstable CAPE.',
            durationMinutes: 50,
            orderIndex: 1,
            isPreview: true,
          },
        ],
      },
    ],
    prerequisites: [],
    competencies: [
      {
        id: 'comp-7',
        name: 'Severe Weather Nowcasting',
        code: 'SEVERE_WEATHER_NOWCASTING',
        category: 'SEVERE_WEATHER',
        targetLevel: 4,
      },
      {
        id: 'comp-8',
        name: 'Disaster Early Warning',
        code: 'DISASTER_EARLY_WARNING',
        category: 'DISASTER_MANAGEMENT',
        targetLevel: 4,
      },
    ],
  },
  {
    id: 'course-5',
    title: 'Ocean-Atmosphere Coupled Dynamics & Monsoon Variability',
    slug: 'ocean-atmosphere-coupled-dynamics',
    description:
      'Advanced study of Indian Ocean sea surface temperature anomalies, Indian Ocean Dipole (IOD), El Niño-Southern Oscillation (ENSO) teleconnections, and intra-seasonal monsoon oscillations.',
    thumbnailUrl: null,
    category: 'OCEAN_SCIENCES',
    difficulty: 'ADVANCED',
    durationMinutes: 2160, // 36 hours
    status: 'PUBLISHED',
    publishedAt: '2024-02-20T00:00:00.000Z',
    isEnrolled: false,
    enrollmentStatus: null,
    trainer: {
      id: 'trainer-5',
      name: 'Dr. S. S. V. S. Ramakrishna',
      designation: 'Senior Ocean Scientist',
      organizationName: 'Indian National Centre for Ocean Information Services (INCOIS)',
      avatarUrl: null,
    },
    modulesCount: 4,
    lessonsCount: 16,
    objectives: [
      'Analyze equatorial wave dynamics (Kelvin and Rossby waves) in the northern Indian Ocean.',
      'Quantify the impact of positive and negative Indian Ocean Dipole modes on monsoon rainfall distribution.',
      'Incorporate Argo float profiles and ocean heat content (OHC) into seasonal prediction models.',
    ],
    modules: [
      {
        id: 'mod-5-1',
        title: 'Module 1: Upper Ocean Thermal Structure and Mixed Layer Dynamics',
        description: 'Ocean heat budget and wind stress coupling.',
        orderIndex: 1,
        lessons: [
          {
            id: 'les-5-1',
            title: 'Ocean Mixed Layer Depth and Barrier Layers',
            description: 'Salinity stratification in the Bay of Bengal.',
            durationMinutes: 55,
            orderIndex: 1,
            isPreview: true,
          },
        ],
      },
    ],
    prerequisites: [
      {
        id: 'prereq-3',
        title: 'Physical Oceanography & Marine Meteorology',
        slug: 'physical-oceanography-marine-met',
        category: 'OCEAN_SCIENCES',
        difficulty: 'INTERMEDIATE',
      },
    ],
    competencies: [
      {
        id: 'comp-9',
        name: 'Ocean-Atmosphere Coupling',
        code: 'OCEAN_ATMOSPHERE_COUPLING',
        category: 'OCEAN_SCIENCES',
        targetLevel: 3,
      },
    ],
  },
  {
    id: 'course-6',
    title: 'Aviation Meteorological Observation & METAR/TAF Standards',
    slug: 'aviation-meteorological-observation',
    description:
      'ICAO Annex 3 and WMO Technical Regulations for aerodrome meteorological observers. Learn standardized coding of METAR, SPECI, and TAF bulletins with precision runway visual range assessments.',
    thumbnailUrl: null,
    category: 'AVIATION_METEOROLOGY',
    difficulty: 'BEGINNER',
    durationMinutes: 1200, // 20 hours
    status: 'PUBLISHED',
    publishedAt: '2024-01-10T00:00:00.000Z',
    isEnrolled: true,
    enrollmentStatus: 'COMPLETED',
    trainer: {
      id: 'trainer-6',
      name: 'Dr. S. K. Roy',
      designation: 'Officer-in-Charge / Aviation Met Office',
      organizationName: 'IMD Aviation Meteorological Division',
      avatarUrl: null,
    },
    modulesCount: 3,
    lessonsCount: 15,
    objectives: [
      'Generate compliant METAR/SPECI reports according to ICAO Annex 3 standards.',
      'Assess cloud amount, base height (ceilometer readings), and Runway Visual Range (RVR).',
      'Issue aerodrome warnings for low-level wind shear, thunderstorms, and runway crosswinds.',
    ],
    modules: [
      {
        id: 'mod-6-1',
        title: 'Module 1: ICAO Regulatory Standards & METAR Syntax',
        description: 'Standardized weather group codes.',
        orderIndex: 1,
        lessons: [
          {
            id: 'les-6-1',
            title: 'Structure of Aerodrome Routine Reports (METAR)',
            description: 'Wind, visibility, weather phenomena, and cloud groups.',
            durationMinutes: 40,
            orderIndex: 1,
            isPreview: true,
          },
        ],
      },
    ],
    prerequisites: [],
    competencies: [
      {
        id: 'comp-10',
        name: 'Aviation Meteorological Reports',
        code: 'AVIATION_MET_REPORTS',
        category: 'AVIATION_METEOROLOGY',
        targetLevel: 3,
      },
    ],
  },
  {
    id: 'course-7',
    title: 'Surface Automatic Weather Station (AWS) Network Calibration',
    slug: 'surface-aws-network-calibration',
    description:
      'Field engineering and instrumentation course on maintenance, telemetry protocols (GPRS/INSAT), sensor diagnostics, and primary calibration for surface meteorological observatories.',
    thumbnailUrl: null,
    category: 'INSTRUMENTATION',
    difficulty: 'BEGINNER',
    durationMinutes: 1440, // 24 hours
    status: 'PUBLISHED',
    publishedAt: '2024-02-25T00:00:00.000Z',
    isEnrolled: false,
    enrollmentStatus: null,
    trainer: {
      id: 'trainer-7',
      name: 'Shri R. K. Giri',
      designation: 'Chief Engineer / Surface Instruments',
      organizationName: 'IMD Instruments Division, Pune',
      avatarUrl: null,
    },
    modulesCount: 3,
    lessonsCount: 14,
    objectives: [
      'Calibrate platinum resistance thermometers (PRT) and capacitive relative humidity sensors against standards.',
      'Maintain tipping-bucket rain gauges with calibrated water drop testing.',
      'Configure INSAT DCP telemetry transmitters for automated hourly observations.',
    ],
    modules: [
      {
        id: 'mod-7-1',
        title: 'Module 1: Sensor Physics & Calibration Chambers',
        description: 'Testing against primary national standards.',
        orderIndex: 1,
        lessons: [
          {
            id: 'les-7-1',
            title: 'Temperature & Humidity Sensor Calibration Procedures',
            description: 'Thermal chamber protocols.',
            durationMinutes: 45,
            orderIndex: 1,
            isPreview: true,
          },
        ],
      },
    ],
    prerequisites: [],
    competencies: [
      {
        id: 'comp-11',
        name: 'AWS Calibration & Maintenance',
        code: 'AWS_CALIBRATION',
        category: 'INSTRUMENTATION',
        targetLevel: 3,
      },
    ],
  },
  {
    id: 'course-8',
    title: 'Aerosol-Cloud Interactions & Climate Radiative Forcing',
    slug: 'aerosol-cloud-climate-forcing',
    description:
      'Study of atmospheric chemistry, aerosol optical depth (AOD), cloud condensation nuclei (CCN), and long-term radiative forcing over South Asia using in-situ ground networks and climate models.',
    thumbnailUrl: null,
    category: 'CLIMATE_SCIENCE',
    difficulty: 'INTERMEDIATE',
    durationMinutes: 1920, // 32 hours
    status: 'PUBLISHED',
    publishedAt: '2024-03-01T00:00:00.000Z',
    isEnrolled: false,
    enrollmentStatus: null,
    trainer: {
      id: 'trainer-8',
      name: 'Dr. G. Pandithurai',
      designation: 'Senior Climate Scientist',
      organizationName: 'Indian Institute of Tropical Meteorology (IITM) Pune',
      avatarUrl: null,
    },
    modulesCount: 4,
    lessonsCount: 16,
    objectives: [
      'Analyze aerosol chemical composition and microphysical properties in monsoon regimes.',
      'Quantify direct and indirect radiative forcing effects on cloud lifetime and precipitation.',
      'Utilize AERONET sun photometer data and satellite lidar (CALIPSO) extinction profiles.',
    ],
    modules: [
      {
        id: 'mod-8-1',
        title: 'Module 1: Atmospheric Aerosol Properties and Measurement',
        description: 'Optical and physical characteristics.',
        orderIndex: 1,
        lessons: [
          {
            id: 'les-8-1',
            title: 'Aerosol Size Distributions and Optical Depth',
            description: 'Mie scattering theory applied to urban aerosols.',
            durationMinutes: 50,
            orderIndex: 1,
            isPreview: true,
          },
        ],
      },
    ],
    prerequisites: [],
    competencies: [
      {
        id: 'comp-12',
        name: 'Climate Radiative Modeling',
        code: 'CLIMATE_MODELING',
        category: 'CLIMATE_SCIENCE',
        targetLevel: 2,
      },
    ],
  },
];

export const mockFilterMetadata: CourseFiltersMetadata = {
  categories: [
    'SATELLITE_METEOROLOGY',
    'NUMERICAL_MODELING',
    'RADAR_METEOROLOGY',
    'SEVERE_WEATHER',
    'OCEAN_SCIENCES',
    'AVIATION_METEOROLOGY',
    'INSTRUMENTATION',
    'CLIMATE_SCIENCE',
  ],
  difficulties: ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'OPERATIONAL'],
  trainers: [
    {
      id: 'trainer-1',
      name: 'Prof. A. Sharma',
      designation: 'Senior Scientist',
      organizationName: 'Space Applications Centre (ISRO)',
      avatarUrl: null,
    },
    {
      id: 'trainer-2',
      name: 'Dr. K. Radhakrishnan',
      designation: 'Lead Scientist',
      organizationName: 'NCMRWF / MoES',
      avatarUrl: null,
    },
    {
      id: 'trainer-3',
      name: 'Smt. P. Verma',
      designation: 'Director / Radar Operations',
      organizationName: 'IMD CTI Pashan',
      avatarUrl: null,
    },
    {
      id: 'trainer-4',
      name: 'Dr. M. Mohapatra',
      designation: 'Director General',
      organizationName: 'IMD HQ New Delhi',
      avatarUrl: null,
    },
    {
      id: 'trainer-5',
      name: 'Dr. S. S. V. S. Ramakrishna',
      designation: 'Senior Ocean Scientist',
      organizationName: 'INCOIS / MoES',
      avatarUrl: null,
    },
    {
      id: 'trainer-6',
      name: 'Dr. S. K. Roy',
      designation: 'Officer-in-Charge',
      organizationName: 'IMD Aviation Met Office',
      avatarUrl: null,
    },
    {
      id: 'trainer-7',
      name: 'Shri R. K. Giri',
      designation: 'Chief Engineer',
      organizationName: 'IMD Instruments Division',
      avatarUrl: null,
    },
    {
      id: 'trainer-8',
      name: 'Dr. G. Pandithurai',
      designation: 'Senior Climate Scientist',
      organizationName: 'IITM Pune',
      avatarUrl: null,
    },
  ],
};
