export interface TopicSeed {
  code: string;
  name: string;
  domainNumber: number;
  domainName: string;
  groupCode: string;
  groupName: string;
  description: string;
  importance: number; // 1.0 to 5.0
  difficulty: number; // 0.1 to 1.0
  estimatedMinutes: number;
  competencyCodes: string[];
}

export const TOPICS_SEED: TopicSeed[] = [
  // ==========================================
  // DOMAIN 1 — Meteorological Fundamentals
  // ==========================================
  {
    code: 'ATM_STRUCT',
    name: 'Atmospheric Structure',
    domainNumber: 1,
    domainName: 'Meteorological Fundamentals',
    groupCode: 'GRP_FUNDAMENTALS',
    groupName: 'Atmospheric Fundamentals & Thermodynamics',
    description: 'Thermal layers of the atmosphere: troposphere, tropopause, stratosphere, mesosphere, composition, and standard atmosphere profile.',
    importance: 4.0,
    difficulty: 0.3,
    estimatedMinutes: 15,
    competencyCodes: ['COMP-SYNOPTIC-MET'],
  },
  {
    code: 'ATM_PRESS',
    name: 'Atmospheric Pressure',
    domainNumber: 1,
    domainName: 'Meteorological Fundamentals',
    groupCode: 'GRP_FUNDAMENTALS',
    groupName: 'Atmospheric Fundamentals & Thermodynamics',
    description: 'Hydrostatic equation, scale height, barometric altimetry, hypsometric equation, and pressure reduction to mean sea level.',
    importance: 4.5,
    difficulty: 0.4,
    estimatedMinutes: 20,
    competencyCodes: ['COMP-SYNOPTIC-MET', 'COMP-INSTRUMENTATION'],
  },
  {
    code: 'ATM_TEMP',
    name: 'Temperature and Heat',
    domainNumber: 1,
    domainName: 'Meteorological Fundamentals',
    groupCode: 'GRP_FUNDAMENTALS',
    groupName: 'Atmospheric Fundamentals & Thermodynamics',
    description: 'Sensible and latent heat transfer, radiative equilibrium, solar insolation, diurnal temperature cycle, and thermal inertia.',
    importance: 4.0,
    difficulty: 0.4,
    estimatedMinutes: 15,
    competencyCodes: ['COMP-SYNOPTIC-MET'],
  },
  {
    code: 'ATM_HUMID',
    name: 'Humidity',
    domainNumber: 1,
    domainName: 'Meteorological Fundamentals',
    groupCode: 'GRP_FUNDAMENTALS',
    groupName: 'Atmospheric Fundamentals & Thermodynamics',
    description: 'Vapor pressure, relative humidity, dew point temperature, mixing ratio, specific humidity, and psychrometric equations.',
    importance: 4.5,
    difficulty: 0.5,
    estimatedMinutes: 20,
    competencyCodes: ['COMP-SYNOPTIC-MET', 'COMP-INSTRUMENTATION'],
  },
  {
    code: 'ATM_STAB',
    name: 'Atmospheric Stability',
    domainNumber: 1,
    domainName: 'Meteorological Fundamentals',
    groupCode: 'GRP_FUNDAMENTALS',
    groupName: 'Atmospheric Fundamentals & Thermodynamics',
    description: 'Dry and saturated adiabatic lapse rates, environmental lapse rate, parcel theory, convective available potential energy (CAPE), and CIN.',
    importance: 5.0,
    difficulty: 0.7,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-SYNOPTIC-MET', 'COMP-RADAR-MET'],
  },
  {
    code: 'ATM_WIND',
    name: 'Wind and Air Motion',
    domainNumber: 1,
    domainName: 'Meteorological Fundamentals',
    groupCode: 'GRP_FUNDAMENTALS',
    groupName: 'Atmospheric Fundamentals & Thermodynamics',
    description: 'Pressure gradient force, Coriolis force, geostrophic balance, gradient wind, thermal wind balance, and boundary layer friction.',
    importance: 4.8,
    difficulty: 0.6,
    estimatedMinutes: 20,
    competencyCodes: ['COMP-SYNOPTIC-MET', 'COMP-NWP-MODELING'],
  },

  // ==========================================
  // DOMAIN 2 — Observation and Instrumentation
  // ==========================================
  {
    code: 'OBS_SURF',
    name: 'Surface Meteorological Observation',
    domainNumber: 2,
    domainName: 'Observation and Instrumentation',
    groupCode: 'GRP_OBSERVATION',
    groupName: 'Surface Observation & Sensor Calibration',
    description: 'Standard meteorological manual observations: stevenson screen, dry/wet bulb thermometers, barometers, anemometers, and SYNOP coding.',
    importance: 4.2,
    difficulty: 0.4,
    estimatedMinutes: 20,
    competencyCodes: ['COMP-INSTRUMENTATION'],
  },
  {
    code: 'OBS_AWS',
    name: 'Automatic Weather Stations',
    domainNumber: 2,
    domainName: 'Observation and Instrumentation',
    groupCode: 'GRP_OBSERVATION',
    groupName: 'Surface Observation & Sensor Calibration',
    description: 'Datalogger hardware architectures, sampling rates, INSAT satellite telemetry transmission, battery/solar power subsystems, and AWS siting.',
    importance: 4.5,
    difficulty: 0.5,
    estimatedMinutes: 20,
    competencyCodes: ['COMP-INSTRUMENTATION'],
  },
  {
    code: 'OBS_RAIN',
    name: 'Rain Gauge Observation',
    domainNumber: 2,
    domainName: 'Observation and Instrumentation',
    groupCode: 'GRP_OBSERVATION',
    groupName: 'Surface Observation & Sensor Calibration',
    description: 'Tipping bucket rain gauge mechanics, optical rain gauges, siphon gauges, catch efficiency errors in wind, and rainfall intensity metrics.',
    importance: 4.0,
    difficulty: 0.3,
    estimatedMinutes: 15,
    competencyCodes: ['COMP-INSTRUMENTATION'],
  },
  {
    code: 'OBS_SENS',
    name: 'Temperature and Humidity Sensors',
    domainNumber: 2,
    domainName: 'Observation and Instrumentation',
    groupCode: 'GRP_OBSERVATION',
    groupName: 'Surface Observation & Sensor Calibration',
    description: 'Platinum resistance thermometers (PT100), capacitive thin-film polymer hygrometers, sensor time constants, and radiation shields.',
    importance: 4.2,
    difficulty: 0.5,
    estimatedMinutes: 20,
    competencyCodes: ['COMP-INSTRUMENTATION'],
  },
  {
    code: 'OBS_CALIB',
    name: 'Instrument Calibration',
    domainNumber: 2,
    domainName: 'Observation and Instrumentation',
    groupCode: 'GRP_OBSERVATION',
    groupName: 'Surface Observation & Sensor Calibration',
    description: 'Traceability to national standards (NPL), calibration chambers, multi-point calibration curves, drift correction, and uncertainty budgets.',
    importance: 4.6,
    difficulty: 0.7,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-INSTRUMENTATION'],
  },
  {
    code: 'OBS_QC',
    name: 'Observation Quality Control',
    domainNumber: 2,
    domainName: 'Observation and Instrumentation',
    groupCode: 'GRP_OBSERVATION',
    groupName: 'Surface Observation & Sensor Calibration',
    description: 'Automated gross limit checks, rate-of-change checks, internal consistency checks, spatial neighborhood comparisons, and QC flagging flags.',
    importance: 4.8,
    difficulty: 0.6,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-INSTRUMENTATION', 'COMP-CLIMATE-SCI'],
  },

  // ==========================================
  // DOMAIN 3 — Weather Analysis
  // ==========================================
  {
    code: 'SYN_MET',
    name: 'Synoptic Meteorology',
    domainNumber: 3,
    domainName: 'Weather Analysis',
    groupCode: 'GRP_ANALYSIS',
    groupName: 'Synoptic Weather Analysis & Remote Sensing',
    description: 'Air masses, source regions, thermal wind advection, baroclinic instability, planetary waves, and jet stream dynamics.',
    importance: 4.8,
    difficulty: 0.6,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-SYNOPTIC-MET'],
  },
  {
    code: 'SYN_MAPS',
    name: 'Weather Maps',
    domainNumber: 3,
    domainName: 'Weather Analysis',
    groupCode: 'GRP_ANALYSIS',
    groupName: 'Synoptic Weather Analysis & Remote Sensing',
    description: 'Isobaric analysis, streamline and isotach analysis, 850, 700, 500, 300, and 200 hPa constant pressure chart diagnostics, and thickness charts.',
    importance: 4.8,
    difficulty: 0.5,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-SYNOPTIC-MET'],
  },
  {
    code: 'SYN_FRONTS',
    name: 'Fronts and Pressure Systems',
    domainNumber: 3,
    domainName: 'Weather Analysis',
    groupCode: 'GRP_ANALYSIS',
    groupName: 'Synoptic Weather Analysis & Remote Sensing',
    description: 'Warm, cold, stationary, and occluded fronts, Western Disturbances over North India, monsoon trough, and mid-tropospheric cyclones.',
    importance: 4.5,
    difficulty: 0.6,
    estimatedMinutes: 20,
    competencyCodes: ['COMP-SYNOPTIC-MET'],
  },
  {
    code: 'SYN_CYCLONE',
    name: 'Cyclone Structure',
    domainNumber: 3,
    domainName: 'Weather Analysis',
    groupCode: 'GRP_ANALYSIS',
    groupName: 'Synoptic Weather Analysis & Remote Sensing',
    description: 'Tropical cyclogenesis thermodynamics, eye, eyewall convection, spiral rainbands, central pressure deficit, and storm surge generation.',
    importance: 5.0,
    difficulty: 0.8,
    estimatedMinutes: 30,
    competencyCodes: ['COMP-SYNOPTIC-MET', 'COMP-OCEAN-SCI'],
  },
  {
    code: 'SYN_THUNDER',
    name: 'Thunderstorm Development',
    domainNumber: 3,
    domainName: 'Weather Analysis',
    groupCode: 'GRP_ANALYSIS',
    groupName: 'Synoptic Weather Analysis & Remote Sensing',
    description: 'Life cycle of convective storm cells: cumulus, mature, dissipating, multicell clusters, supercell dynamics, gust fronts, and downbursts.',
    importance: 4.8,
    difficulty: 0.7,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-SYNOPTIC-MET', 'COMP-RADAR-MET'],
  },
  {
    code: 'RAD_FUND',
    name: 'Weather Radar Fundamentals',
    domainNumber: 3,
    domainName: 'Weather Analysis',
    groupCode: 'GRP_ANALYSIS',
    groupName: 'Synoptic Weather Analysis & Remote Sensing',
    description: 'Radar equation for meteorology, equivalent reflectivity factor Z, attenuation at S/C/X bands, radial Doppler velocity, and beam refraction.',
    importance: 4.8,
    difficulty: 0.6,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-RADAR-MET'],
  },
  {
    code: 'SAT_FUND',
    name: 'Satellite Meteorology Fundamentals',
    domainNumber: 3,
    domainName: 'Weather Analysis',
    groupCode: 'GRP_ANALYSIS',
    groupName: 'Synoptic Weather Analysis & Remote Sensing',
    description: 'Geostationary vs polar orbits, visible, thermal infrared (TIR), and water vapor (WV) spectral channels, and brightness temperature conversion.',
    importance: 4.7,
    difficulty: 0.6,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-SAT-MET'],
  },

  // ==========================================
  // DOMAIN 4 — Forecasting
  // ==========================================
  {
    code: 'NWP_FUND',
    name: 'Numerical Weather Prediction Fundamentals',
    domainNumber: 4,
    domainName: 'Forecasting',
    groupCode: 'GRP_FORECASTING',
    groupName: 'Forecasting & Numerical Modeling',
    description: 'Primitive equations, grid structures (Arakawa grids), numerical integration schemes, CFL stability criterion, and boundary conditions.',
    importance: 4.9,
    difficulty: 0.8,
    estimatedMinutes: 30,
    competencyCodes: ['COMP-NWP-MODELING'],
  },
  {
    code: 'NWP_ENSEMBLE',
    name: 'Ensemble Forecasting',
    domainNumber: 4,
    domainName: 'Forecasting',
    groupCode: 'GRP_FORECASTING',
    groupName: 'Forecasting & Numerical Modeling',
    description: 'Initial condition perturbation methods (singular vectors, bred vectors), ensemble spread vs skill, probability of exceedance, and spaghetti plots.',
    importance: 4.7,
    difficulty: 0.7,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-NWP-MODELING'],
  },
  {
    code: 'FCST_NOWCAST',
    name: 'Nowcasting',
    domainNumber: 4,
    domainName: 'Forecasting',
    groupCode: 'GRP_FORECASTING',
    groupName: 'Forecasting & Numerical Modeling',
    description: '0 to 6 hour extrapolation of radar echoes (TITAN/TREC), cross-correlation tracking, satellite cloud top cooling rate, and lightning jump.',
    importance: 5.0,
    difficulty: 0.8,
    estimatedMinutes: 30,
    competencyCodes: ['COMP-RADAR-MET', 'COMP-SYNOPTIC-MET'],
  },
  {
    code: 'FCST_SHORTRANGE',
    name: 'Short-Range Forecasting',
    domainNumber: 4,
    domainName: 'Forecasting',
    groupCode: 'GRP_FORECASTING',
    groupName: 'Forecasting & Numerical Modeling',
    description: '12 to 72 hour weather prediction integrating high-resolution WRF model guidance with local surface and upper air observations.',
    importance: 4.8,
    difficulty: 0.7,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-SYNOPTIC-MET', 'COMP-NWP-MODELING'],
  },
  {
    code: 'FCST_VERIF',
    name: 'Forecast Verification',
    domainNumber: 4,
    domainName: 'Forecasting',
    groupCode: 'GRP_FORECASTING',
    groupName: 'Forecasting & Numerical Modeling',
    description: 'Contingency tables, Probability of Detection (POD), False Alarm Ratio (FAR), Critical Success Index (CSI), Brier Score, and ROC curves.',
    importance: 4.7,
    difficulty: 0.6,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-NWP-MODELING', 'COMP-CLIMATE-SCI'],
  },
  {
    code: 'FCST_PROB',
    name: 'Probabilistic Forecasting',
    domainNumber: 4,
    domainName: 'Forecasting',
    groupCode: 'GRP_FORECASTING',
    groupName: 'Forecasting & Numerical Modeling',
    description: 'Quantifying atmospheric uncertainty, probability density functions (PDF), reliability diagrams, and cost-loss economic decision modeling.',
    importance: 4.5,
    difficulty: 0.7,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-NWP-MODELING'],
  },

  // ==========================================
  // DOMAIN 5 — Climate and Data
  // ==========================================
  {
    code: 'CLIM_VAR',
    name: 'Climate Variability',
    domainNumber: 5,
    domainName: 'Climate and Data',
    groupCode: 'GRP_CLIMATE',
    groupName: 'Climate Variability & Data Quality',
    description: 'El Niño Southern Oscillation (ENSO), Indian Ocean Dipole (IOD), Madden-Julian Oscillation (MJO), and Pacific Decadal Oscillation.',
    importance: 4.7,
    difficulty: 0.6,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-CLIMATE-SCI', 'COMP-SYNOPTIC-MET'],
  },
  {
    code: 'CLIM_CHANGE',
    name: 'Climate Change Fundamentals',
    domainNumber: 5,
    domainName: 'Climate and Data',
    groupCode: 'GRP_CLIMATE',
    groupName: 'Climate Variability & Data Quality',
    description: 'Radiative forcing, greenhouse gas concentration pathways, warming trends in the Indian subcontinent, and extreme event intensification.',
    importance: 4.4,
    difficulty: 0.5,
    estimatedMinutes: 20,
    competencyCodes: ['COMP-CLIMATE-SCI'],
  },
  {
    code: 'CLIM_QC',
    name: 'Climate Data Quality',
    domainNumber: 5,
    domainName: 'Climate and Data',
    groupCode: 'GRP_CLIMATE',
    groupName: 'Climate Variability & Data Quality',
    description: 'Homogenization of long-term climatological time series, detection of non-climatic shifts (station relocations, instrument changes), and gap-filling.',
    importance: 4.6,
    difficulty: 0.6,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-CLIMATE-SCI', 'COMP-INSTRUMENTATION'],
  },
  {
    code: 'CLIM_INDICES',
    name: 'Climate Indices',
    domainNumber: 5,
    domainName: 'Climate and Data',
    groupCode: 'GRP_CLIMATE',
    groupName: 'Climate Variability & Data Quality',
    description: 'ETCCDI extreme temperature and precipitation indices: CDD, CWD, R95p, TXx, TNn, heat wave duration index, and drought SPI calculations.',
    importance: 4.5,
    difficulty: 0.6,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-CLIMATE-SCI'],
  },
  {
    code: 'CLIM_TIMESERIES',
    name: 'Time-Series Analysis',
    domainNumber: 5,
    domainName: 'Climate and Data',
    groupCode: 'GRP_CLIMATE',
    groupName: 'Climate Variability & Data Quality',
    description: 'Mann-Kendall trend test, Sen slope estimator, autocorrelation, spectral wavelet analysis, and seasonal decomposition of climate anomalies.',
    importance: 4.6,
    difficulty: 0.7,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-CLIMATE-SCI'],
  },
  {
    code: 'CLIM_INTERP',
    name: 'Meteorological Data Interpretation',
    domainNumber: 5,
    domainName: 'Climate and Data',
    groupCode: 'GRP_CLIMATE',
    groupName: 'Climate Variability & Data Quality',
    description: 'Multivariate statistical synthesis, spatial interpolation techniques (Kriging, Barnes objective analysis), and NetCDF visualization in CDO/Python.',
    importance: 4.7,
    difficulty: 0.7,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-CLIMATE-SCI', 'COMP-NWP-MODELING'],
  },

  // ==========================================
  // DOMAIN 6 — Operational Applications
  // ==========================================
  {
    code: 'OPS_WARNING',
    name: 'Severe Weather Warning',
    domainNumber: 6,
    domainName: 'Operational Applications',
    groupCode: 'GRP_OPERATIONAL',
    groupName: 'Operational Applications & Warning Systems',
    description: 'Color-coded warning protocols (Green, Yellow, Orange, Red), heavy rainfall thresholds, heatwave advisories, and cyclone bulletin templates.',
    importance: 5.0,
    difficulty: 0.7,
    estimatedMinutes: 30,
    competencyCodes: ['COMP-SYNOPTIC-MET', 'COMP-RADAR-MET'],
  },
  {
    code: 'OPS_DISASTER',
    name: 'Disaster Risk Information',
    domainNumber: 6,
    domainName: 'Operational Applications',
    groupCode: 'GRP_OPERATIONAL',
    groupName: 'Operational Applications & Warning Systems',
    description: 'Integration of meteorological hazard warnings with NDMA/SDMA emergency operations, vulnerability maps, and impact-based forecasting.',
    importance: 4.6,
    difficulty: 0.5,
    estimatedMinutes: 20,
    competencyCodes: ['COMP-SYNOPTIC-MET', 'COMP-OCEAN-SCI'],
  },
  {
    code: 'OPS_AVIATION',
    name: 'Aviation Meteorology',
    domainNumber: 6,
    domainName: 'Operational Applications',
    groupCode: 'GRP_OPERATIONAL',
    groupName: 'Operational Applications & Warning Systems',
    description: 'METAR, SPECI, TAF generation, low-level wind shear, clear air turbulence (CAT), aircraft icing, runway visual range (RVR), and SIGMET.',
    importance: 4.8,
    difficulty: 0.8,
    estimatedMinutes: 30,
    competencyCodes: ['COMP-SYNOPTIC-MET', 'COMP-RADAR-MET'],
  },
  {
    code: 'OPS_HYDRO',
    name: 'Hydrometeorological Applications',
    domainNumber: 6,
    domainName: 'Operational Applications',
    groupCode: 'GRP_OPERATIONAL',
    groupName: 'Operational Applications & Warning Systems',
    description: 'Quantitative Precipitation Forecasts (QPF), catchment rainfall estimation, Flash Flood Guidance (FFG), and dam outflow decision coordination.',
    importance: 4.7,
    difficulty: 0.7,
    estimatedMinutes: 25,
    competencyCodes: ['COMP-SYNOPTIC-MET', 'COMP-RADAR-MET'],
  },
  {
    code: 'OPS_COMM',
    name: 'Weather Communication',
    domainNumber: 6,
    domainName: 'Operational Applications',
    groupCode: 'GRP_OPERATIONAL',
    groupName: 'Operational Applications & Warning Systems',
    description: 'Communicating atmospheric uncertainty to media, public alerts via Common Alerting Protocol (CAP-CP), and crisis communication strategies.',
    importance: 4.2,
    difficulty: 0.4,
    estimatedMinutes: 15,
    competencyCodes: ['COMP-SYNOPTIC-MET'],
  },
  {
    code: 'OPS_DECISION',
    name: 'Forecast Decision Support',
    domainNumber: 6,
    domainName: 'Operational Applications',
    groupCode: 'GRP_OPERATIONAL',
    groupName: 'Operational Applications & Warning Systems',
    description: 'Multi-criteria operational matrix, briefing emergency managers, operational shift handovers, and high-impact weather post-mortems.',
    importance: 4.8,
    difficulty: 0.6,
    estimatedMinutes: 20,
    competencyCodes: ['COMP-SYNOPTIC-MET', 'COMP-NWP-MODELING'],
  },
];
